number1 = input("Pleasee enter an integer and press enter: ")
number2 = input("Please type another integer and press enter: ")
number1 = int(number1)
number2 = int(number2)
print('Number1 ** Number2 =', number1 ** number2)